---
title: "EBDM"
description: |
  Welcome to the website for *Evidence-based decision making* FS25 ([11230-01](https://vorlesungsverzeichnis.unibas.ch/de/vorlesungsverzeichnis?id=289121))
  
  Instructors: [Loreen Tisdall](https://loreentisdall.github.io) and [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), University of Basel
  
  Last updated `r format(Sys.time(), "%a %b %d %X %Y")`
#site: distill::distill_website

    
output: 
  distill::distill_article:
    md_extensions: +emoji
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

![Very much like a spread of tools, science offers a plethora of strategies... <br> <span>photo by <a href="https://unsplash.com/@carlevarino?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Cesar Carlevarino Aragon</a> on <a href="https://unsplash.com/s/photos/tools?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>](photos/cesar-carlevarino-aragon-NL_DF0Klepc-unsplash.jpg)

# :busstop: Session information

Sessions take place Mondays, 14.15-15.45 in different locations (see table below; Kollegie = Kollegienhaus, Hörsaal 120; Missionsstr. = Missionsstrasse 62a, Seminarraum 00.006; Chemie = Chemie, Organische, Grosser Hörsaal OC).  

::: l-body
| # | Date     | Topic                         | Slides | Location | Instructor |
|---| ---------|-------------------------------|--------| --------| --------|
| 1 | 17.02.2025 | [The scientific method(s)](session1.html) |[pdf](presentations/EBDM_session1.pdf)| Kollegien | Mata|
| 2 | 24.02.2025 | [Algorithms: The power of algorithms](session2.html) |[pdf](presentations/EBDM_session2.pdf) | Kollegien | Mata|
| 3 | 17.03.2025 | [Algorithms: The problems of algorithms](session3.html) |[pdf](presentations/EBDM_session3.pdf) | Missionsstr. | Mata|
| 4 | 24.03.2025 | [Consensus: The wisdom of the crowd](session4.html) |[pdf](presentations/EBDM_session4.pdf) | Missionsstr. | Tisdall|
| 5 | 31.03.2025 | [Consensus: The wisdom of experts](session5.html) |[pdf](presentations/EBDM_session5.pdf) | Missionsstr. | Tisdall|
| 6 | 07.04.2025 | [Counterfactuals: Experiments](session6.html) |[pdf](presentations/EBDM_session6.pdf) | Missionsstr. | Tisdall|
| 7 | 14.04.2025 | [Counterfactuals: Alternatives to experiments](session7.html) |[pdf](presentations/EBDM_session7.pdf) | Missionsstr. | Tisdall|
| 8 | 28.04.2025 | [Synthesis: Overview](session8.html) |[pdf](presentations/EBDM_session8.pdf) | Missionsstr. | Mata|
| 9 | 05.05.2025 | [Synthesis: Limitations](session9.html) |[pdf](presentations/EBDM_session9.pdf) | Missionsstr. | Mata|
| 10 | 12.05.2025 | [Interventions: A taxonomy](session10.html) |[pdf](presentations/EBDM_session10.pdf) | Missionsstr. | Mata|
| 11 | 19.05.2025 | [Interventions: Implementation](session11.html) |[pdf](presentations/EBDM_session11.pdf) | Missionsstr. | Mata|
| 12 | 26.05.2025 | [Exam](exam.html) | | Chemie | |
:::

*Note*. Slides will be made available shortly before each session. For some sessions, the slides available may be from previous versions of the course (FS24).

# :books: What is this course about? 

As the name implies, this course is about **evidence-based decision making**. The main premise of the course is that informed decisions require the use of evidence (i.e., data that has been processed in some way to generate knowledge or insight). 

The behavioral sciences, such as psychology and economics, have developed a number of concepts and techniques - a methodological toolbox - designed to transform data into evidence. This course aims to unpack some of these tools and showcase how they can be used in practice. 

The overarching theme of the course is that evidence-based decision making uses the tools of SCIENCE to help us make better, informed decisions. This theme is reflected in the structure of the course: After the first introductory session, the course is divided into modules covering 5 different scientific "methods", specifically, the benefits and limits of formalization (**Algorithms**), the discussion and amalgamation of diverse opinions (**Consensus**), the use of experiments and other methods to infer causality (**Counterfactuals**), the comprehensive and unbiased summary of multiple studies (**Synthesis**), and the implementation of interventions based on the best possible evidence (**Interventions**). 

# :school_satchel: What can you expect to learn? 

The course will cover broad theoretical principles of evidence-based decision making. The principles will be illustrated with examples, inclduing at least one simple tutorial with example code in [R](https://www.r-project.org), and other recommended exercises designed to facilitate understanding of the underlying concepts.

### By completing the course you can expect to LEARN... 

- central concepts in evidence-based decision making
- general principles of causal inference
- basic statistical concepts (e.g., aggregation, bias)
- guidelines for conducting and reporting scientific procedures  
- a taxonomy of behavioral interventions
- many practical and positive examples of evidence-based practices

### you will NOT, however, receive training in...

- mathematical analysis
- advanced programming skills 

# :beginner: How should you use this website? 

This website is designed to help course participants get an overview of the course and access the course materials. Each session typically includes a background video, some required reading (typically 1 academic paper), and the course slides. Note that course slides may be updated after each session. 

No video recordings of the in-person sessions will be made available. 

Information about the exam is available on the [Exam](exam.html) tab on this webpage.  
